### PR TITLE
Expand the accepted character set for literals

### LINKED ISSUE #39: google.com:<name> should be a valid project name to instantiate PathTemplate
Tried to instantiate PathTemplate, but it fails with the following stack trace:

ERROR:root:match error: impossible match
Traceback (most recent call last):
  File "example.py", line 14, in run
    project_name = PubApi.project_path(project_id)
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/gcloud/pubsub/publisher_api.py", line 57, in project_path
    return cls._PROJECT_PATH_TEMPLATE.instantiate({'project': project, })
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/.tox/py27/local/lib/python2.7/site-packages/google/gax/path_template.py", line 125, in\
 instantiate
    self.match(path)
  File "/usr/local/google/home/jgeiger/xnewgitonborg/gapi-dev/gapi-pubsub-python/.tox/py27/local/lib/python2.7/site-packages/google/gax/path_template.py", line 170, in\
 match
    raise ValidationException('match error: impossible match')
ValidationException: match error: impossible match

### PR DESCRIPTION
**Pull request by saicheems**
Remove support for custom verbs (only useful for HTTP).

Resolves #39

### CODE REVIEW

**Comment by tbetbetbe** [comment]
github-fu: you should include 'Fixes #39' in the initial comment, then when this pull is merged, #39 will get closed.

**Comment by saicheems** [comment]
Yup, I think resolves does it as well

**Comment by saicheems** [comment]
Pls don't merge this yet

**Comment by saicheems** [comment]
Ready for review

**Comment by saicheems** [comment]
@geigerj

**Comment by tbetbetbe** [comment]
LGTM

**Pull request merged**
