### PR TITLE
Add new Future package google.gax.future

### LINKED ISSUE #194: OperationFuture should not use fork and multiprocessing
Our present implementation of `OperationFuture.add_done_callback` has two branches with vastly different behavior:

1. If the operation is already done, it will immediately invoke the callback on the main process. This is in line with `asyncio` and `concurrent.futures`.
2. If the operation is *not* already done, it will *fork* and spawn a separate process to do a blocking poll on the operation. When the operation is complete, it will invoke the callback **on the forked process**.

The second behavior is problematic for several reasons:

1. It violates principle of least astonishment. A user does not expect their process to be forked and that the callback could potentially be called on a forked process. In fact, `concurrent.futures.ProcessPoolExecutor` goes [out of its way](https://github.com/python/cpython/blob/0edffa3073b551ffeca34952529e7b292f1bd350/Lib/concurrent/futures/process.py#L313) to ensure that callbacks are executed on the process that starts the pool, not in the processes owned by the pool.
2. Forking behavior is undesirable. First and foremost, it causes an entire copy of the process just to handle a simple non-blocking poll. Additionally, forking a multithreaded process is [problematic](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) and gRPC's c-core uses threads by design. Finally, gRPC does not support being forked and [barfs](https://gist.github.com/jonparrott/9c1d229adb43388fb81afca29af28c72) when the connection gets corrupted (by some saving grace, either our retries or gRPC's own logic, gRPC can re-establish the connection in the forked process).

We should just use a thread for this. There's no benefit to us using multiprocessing for this case. 

Bonus: we can drop `dill` as a dependency.

### PR DESCRIPTION
**Pull request by jonparrott**
* Add new abstract base class google.gax.future.base.Future.
* Add base class for polling-style futures google.gax.future.base.PollingFuture.
* Add class for gRPC-based long-running operations google.gax.future.grpc_operation_future.OperationFuture.
* Remove google.gax._OperationFuture.
* Remove google.gax._from_any.
* Remove dependency on dill.

This decouples the concepts of a Future, a Future that polls, and a Future that polls using gRPC for a LRO. It leaves the door open to the possibility of other types of Futures and also implementing an LRO future without gRPC.

This is a *breaking* change as written. The code generator will need to be updated to use this new future class. However, based on usage it's likely safe to alias the old name google.gax._OperationFuture to the new google.gax.future.grpc_operation_future.OperationFuture. I can do that if we think it's necessary.

Resolves #194.

/cc @dhermes who I bounced this off of.

### CODE REVIEW

**Comment by jonparrott** [comment]
Alright, @lukesneeringer, this should be ready for review.

**Comment by lukesneeringer** [comment]
> This is a _breaking_ change as written. The code generator will need to be updated to use this new future class. However, based on usage it's likely safe to alias the old name google.gax._OperationFuture to the new google.gax.future.grpc_operation_future.OperationFuture. I can do that if we think it's necessary.

Summoning @dhermes.

Ideally I would prefer not do this and get everything migrated, but that is likely to be something of a process. Would it be better to alias for a couple releases?

**Comment by dhermes** [comment]
Why do you think it'd be "something of a process"? We have version pinning for the GAPICs we depend on. Do they in turn have version pinning for GAX?

**Comment by jonparrott** [comment]
closing in favor of https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3616

**Pull request closed without merging**
