### PR TITLE
Make grpc preferentially use google-auth for authentication

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by jonparrott** [comment]
@geigerj last one. :)

**Comment by geigerj** [comment]
@jonparrott Thanks for all the help with this transition! :)

**Comment by jonparrott** [comment]
Thank you, any idea when the next major release of gax will be? Once that happens I can start transitioning google-cloud-python.

**Comment by geigerj** [comment]
@bjwatson Could you comment on the plans here?

This past sequence of commits changes the public surface of GAX, so we will need to update the code generator templates and release new versions of the GAPIC libraries for `google-cloud-python` to be able to pick these changes up. It will be more efficient to bundle the regeneration together with a few other breaking changes to GAX/GAPIC that are en route, but that might also mean more time -- probably closer to EOQ.

If it's needed sooner, we can do the regeneration for the auth changes separately.

**Comment by jonparrott** [comment]
I (ideally) want to put the steps in place to deprecate oauth2client this
quarter, but if it's prohibitive for you guys to do so, that's okay.

If it's no prohibitive it would be super cool if we could make this happen
by December.

**Comment by bjwatson** [comment]
I'd like to hold off for another couple weeks before rolling the next release of GAX and rebuilding all the GAPIC layers, so that we can include other features we're working on. Let's target the week of Thanksgiving.

**Comment by jonparrott** [comment]
Sounds good. Thanks, guys!

**Pull request merged**
