### PR TITLE
Rename path template `instantiate` to `render`

### PR DESCRIPTION
**Pull request by geigerj**
Fixes #93 

Corresponding codegen change is googleapis/toolkit#19

### CODE REVIEW

**Comment by geigerj** [comment]
@bjwatson @jmuk

**Comment by tbetbetbe** [comment]
Please add a minor version bump.

**Comment by geigerj** [comment]
Version bumped.

**Comment by tbetbetbe** [comment]
LGTM

**Comment by geigerj** [comment]
I will merge this when googleapis/toolkit#19 is approved

**Comment by bjwatson** [comment]
LGTM

**Pull request merged**
