### PR TITLE
Include license

### PR DESCRIPTION
**Pull request by bjwatson**
@geigerj PTAL, then I'll publish a release so @tseaver can [re-enable bundling](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1911).

### CODE REVIEW

**Comment by bjwatson** [comment]
FYI, https://github.com/googleapis/gax-python/pull/116/files is a bit bigger to review, so that can wait until a `0.12.3` release.

**Comment by geigerj** [comment]
LGTM

**Comment by bjwatson** [comment]
@geigerj I just updated dependencies on protobuf and grpcio, also. PTAL

**Comment by geigerj** [comment]
LGTM

**Pull request merged**
