### PR TITLE
Roll new release with preference for new google-auth library.

### PR DESCRIPTION
**Pull request by bjwatson**
This still uses oauth2client by default, but will use
https://pypi.python.org/pypi/google-auth if installed.

Set upper bounds on dependencies to avoid future surprises.

FYI @jonparrott @dhermes

### CODE REVIEW

**Comment by jonparrott** [comment]
👍

**Comment by geigerj** [comment]
Note that we should not update the `packman` configuration until GAPIC has also been updated to use the new auth surface.

**Comment by bjwatson** [comment]
@geigerj Do you see any problems with updating `packman` to use this version, as long as it does not add a `google-auth` dependency?

**Comment by geigerj** [comment]
Yes, #135 changed the public interface of GAX, so codegen needs some superficial updates before it can depend on `GAX 0.15.0`. I can do that tomorrow and then update `packman` if that works?

**Comment by bjwatson** [comment]
SGTM

**Pull request merged**
