### PR TITLE
Add metadata_overlay

### PR DESCRIPTION
**Pull request by eoogbe**
To be used in the routing header like this:
```
self._create_book = api_callable.create_api_call(
            self.library_service_stub.CreateBook,
            settings=defaults['create_book'],
            metadata_overlay=lambda req: {
                b'x-google-request-params':
                    b'name={}&book.read={}'.format(req.name, req.book.read)})
```

### CODE REVIEW

**Comment by jonparrott** [comment]
Hey @eoogbe, should this be done against api_core instead? (we're about to drop gax)

**Comment by eoogbe** [comment]
@jonparrott When you say "about to", how soon do you mean? Routing headers are pretty critical path.

**Comment by jonparrott** [comment]
@lukesneeringer and @landrito can speak to that.

**Comment by jonparrott** [comment]
@eoogbe I also thought about this a while and I can't see why we need this. Metadata can already be specified by gapic clients in the generated method.

For example, we could update this generated code:

```python
def create_book(self, name, read=False, ...):
    request = book_pb2.Book(
        name=name,
        read=read,
    )

    return self._create_book(request, ...)
```

to just this:

```python
def create_book(self, name, read=False, ...):
    request = book_pb2.Book(
        name=name,
        read=read,
    )

    metadata = [
        ('x-google-request-params',
         'name={}&book.read={}'.format(request.name, request.read)),
    ]

    return self._create_book(
        request, metadata=metadata, ...)
```

Therefore obviating the need for this complex "overlay" logic. Am I missing something?

**Comment by eoogbe** [comment]
@jonparrott Fair enough

**Comment by jonparrott** [comment]
Cool - glad we could figure out a simpler solution. :)

**Pull request closed without merging**
