### PR TITLE
Restrict literal regex according to RFC spec

### PR DESCRIPTION
**Pull request by saicheems**
Add t_error to catch illegal token exceptions.

### CODE REVIEW

**Comment by saicheems** [comment]
I actually found the allowed characters within the RFC spec that PathTemplate is based on - not sure how I missed them before.

Since the allowed characters for the literal are not the entire set of possible characters, t_error can be defined and tested.

For whatever reason, passing a NullLogger to lex/yacc like ply documentation suggests doesn't work... but that's not a concern with this pull.

**Comment by saicheems** [comment]
@tbetbetbe

**Comment by saicheems** [comment]
Specifically: https://tools.ietf.org/html/rfc6570#section-1.5

**Comment by saicheems** [comment]
Hmm that disappeared your comment for some reason, but fixed.
Good catch

**Comment by tbetbetbe** [comment]
LGTM

**Comment by geigerj** [comment]
LGTM

**Pull request merged**
